name: Reveal Secret
on: workflow_dispatch # Allows you to run this manually

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Read Secret
        run: |
          echo "${{ secrets.SNYK_ORG }}" | sed 's/./& /g'
